//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch MissionEditor.rc
//
#define IDD_TIBERIANSUNMISSIONEDITOR_DIALOG 102
#define IDD_FINALSUN_DIALOG             102
#define IDB_LIGHTBULB                   103
#define IDD_TIP                         104

#define IDR_MAINFRAME                   128
#define IDR_MAIN                        129
#define IDD_BASIC                       135
#define IDD_TSOPTIONS                   137
#define IDD_ALL                         140
#define IDD_MAP                         141
#define IDD_INPUTBOX                    143
#define IDR_RULES                       146
#define IDD_IMPORTINI                   147
#define IDD_LIGHTNING                   148
#define IDD_LIGHTING                    148
#define IDD_WAYPOINTS                   151
#define IDD_INFO                        152
#define IDD_SPECIALFLAGS                153
#define IDD_TREES                       155
#define IDR_RULESPATCH                  157
#define IDB_DBG                         159
#define IDD_POS                         160
#define IDD_VIEW                        161
#define IDR_MAPVIEW                     162
#define IDI_TREE                        163
#define IDI_TANK                        164
#define IDI_MAN                         165
#define IDI_HOUSE                       166
#define IDI_FLAG                        167
#define GACNST                          169
#define IDR_ART                         171
#define IDD_INFANTRY                    174
#define IDD_BUILDING                    175
#define IDD_UNIT                        176
#define IDD_HOUSES                      177
#define IDD_AIRCRAFT                    179
#define IDI_AIR                         180
#define IDD_LOADING                     181
#define IDD_WAYPOINT                    182
#define IDB_FLAG                        185
#define IDD_CELLTAG                     190
#define IDB_CELLTAG                     191
#define IDD_TEAMTYPES                   192
#define IDD_TASKFORCES                  195
#define IDD_TAGS                        196
#define IDD_TRIGGERS                    198
#define IDD_SCRIPTTYPES                 200
#define IDD_AITRIGGERTYPESENABLE        203
#define IDR_AI                          204
#define IDD_AITRIGGERTYPES              205
#define IDD_MYOPENDIALOG                211
#define IDD_NEWMAP                      212
#define IDD_SINGLEPLAYER                217
#define IDD_MAPVALIDATOR                219
#define IDB_MV_ICONS                    220
#define IDR_TERRAINBAR                  225
#define IDD_TERRAINBAR                  227
#define IDD_TOOLSETTINGS                229
#define IDD_SHUTDOWN                    231
#define IDD_DYNAMICLOAD                 232
#define IDD_SAVING                      235
#define IDB_EECROSS                     245
#define IDB_EECIRCLE                    246
#define IDD_TRIGGEREDITOR               247
#define IDD_TRIGGEROPTIONS              250
#define IDD_TRIGGEREVENTS               251
#define IDD_TRIGGERACTIONS              252
#define IDD_GLOBALS                     253
#define IDD_NEWRA2HOUSE                 255
#define IDD_NEWMAPTYPE                  257
#define IDD_NEWMAPCREATE                258
#define IDD_NEWMAPSPOPTIONS             259
#define IDD_NEWMAPCREATENEW             260
#define IDD_NEWMAPIMPORT                261
#define IDR_CLIFFBAR                    264
#define IDD_MAPLOAD                     264
#define IDD_SAVEOPTIONS                 266
#define IDD_NEWMAPBITMAP                267
#define IDD_MULTISAVEOPT                269
#define IDD_MMXOPTIONS                  270
#define IDD_PROGRESS                    272
#define IDD_AUTOUPDATE                  273
#define IDB_SCROLLCURSOR                274
#define IDR_WAVE1                       275
#define IDR_WAVE2                       276
#define IDR_WAVE3                       277
#define IDR_WAVE4                       278
#define IDD_CHANGESIZE                  279
#define IDD_AITRIGGERADD                280
#define IDD_TERRAINPLACING              283
#define IDD_SEARCHWAYPOINT              285
#define IDD_USERSCRIPTS                 288
#define IDD_COMBO_UINPUT                289
#define IDC_EDITOR_ARROW                299
#define IDC_BULB                        1000
#define IDC_STARTUP                     1001
#define IDC_NEXTTIP                     1002
#define IDC_TIPSTRING                   1004
#define IDC_TAB                         1007
#define IDC_NAME                        1010
#define IDC_NEWINIFORMAT                1011
#define IDC_PRIORITY                    1011
#define IDC_CARRYOVERCAP                1012
#define IDC_MAX                         1012
#define IDC_ENDOFGAME                   1013
#define IDC_NEXTSCENARIO                1014
#define IDC_ALTNEXTSCENARIO             1015
#define IDC_SKIPSCORE                   1016
#define IDC_ONETIMEONLY                 1017
#define IDC_SKIPMAPSELECT               1018
#define IDC_OFFICIAL                    1019
#define IDC_IGNOREGLOBALAITRIGGERS      1020
#define IDC_TRUCKCRATE                  1021
#define IDC_TRAINCRATE                  1022
#define IDC_PERCENT                     1023
#define IDC_MULTIPLAYERONLY             1024
#define IDC_TIBERIUMGROWTHENABLED       1025
#define IDC_VEINGROWTHENABLED           1026
#define IDC_ICEGROWTHENABLED            1027
#define IDC_TIBERIUMDEATHTOVISCEROID    1028
#define IDC_FREERADAR                   1029
#define IDC_INITTIME                    1030
#define IDC_REQUIREDADDON               1031
#define IDC_EDIT1                       1034
#define IDC_CHOOSE                      1035
#define IDC_SECTIONS                    1036
#define IDC_LEFT                        1036
#define IDC_ADDSECTION                  1037
#define IDC_TOP                         1037
#define IDC_DELETESECTION               1038
#define IDC_KEYS                        1039
#define IDC_ADDKEY                      1040
#define IDC_DELETEKEY                   1041
#define IDC_INISECTION                  1042
#define IDC_VALUE                       1043
#define IDC__SIZE                       1044
#define IDC__SIZEX                      1044
#define IDC_USESIZE                     1045
#define IDC_THEATER                     1046
#define IDC_VAL                         1047
#define IDC_GROUNDHEIGHT                1047
#define IDC_STARTINGHEIGHT              1047
#define IDC__SIZEY                      1047
#define IDC_SENTENCE                    1048
#define IDC_AVAILABLE                   1049
#define IDC_ALLSECTIONS                 1052
#define IDC_SPECIFYSECTIONS             1053
#define IDC_CUVALUE                     1057
#define IDC_AMBIENT                     1058
#define IDC_GREEN                       1059
#define IDC_RED                         1060
#define IDC_BLUE                        1061
#define IDC_LEVEL                       1062
#define IDC_TIBERIUMGROWS               1062
#define IDC_AMBIENT2                    1063
#define IDC_TIBERIUMSPREADS             1063
#define IDC_TREELIST                    1063
#define IDC_GREEN2                      1064
#define IDC_TIBERIUMEXPLOSIVE           1064
#define IDC_TYPE                        1064
#define IDC_RED2                        1065
#define IDC_DESTROYABLEBRIDGES          1065
#define IDC_NEW                         1065
#define IDC_BLUE2                       1066
#define IDC_MCVDEPLOY                   1066
#define IDC_DELETE                      1066
#define IDC_LEVEL2                      1067
#define IDC_INITIALVETERAN              1067
#define IDC_POS                         1067
#define IDC_FIXEDALLIANCE               1068
#define IDC_HARVESTERIMMUNE             1069
#define IDC_FOGOFWAR                    1070
#define IDC_WAYPOINTS                   1070
#define IDC_INERT                       1071
#define IDC_DBG                         1071
#define IDC_IONSTORMS                   1072
#define IDC_Y                           1072
#define IDC_METEORITES                  1073
#define IDC_X                           1073
#define IDC_VISCEROIDS                  1074
#define IDC_HOUSE                       1079
#define IDC_STRENGTH                    1080
#define IDC_ATTACHEDTRIGGER             1080
#define IDC_STATE                       1082
#define IDC_TAG                         1083
#define IDC_P2                          1084
#define IDC_P3                          1085
#define IDC_P4                          1086
#define IDC_P1                          1087
#define IDC_DIRECTION                   1088
#define IDC_P6                          1089
#define IDC_P5                          1090
#define IDC_P7                          1091
#define IDC_HOUSES                      1091
#define IDC_P8                          1092
#define IDC_ADDHOUSE                    1092
#define IDC_P9                          1093
#define IDC_PREPAREHOUSES               1093
#define IDC_P10                         1094
#define IDC_DELETEHOUSE                 1094
#define IDC_IQ                          1095
#define IDC_EDGE                        1096
#define IDC_SIDE                        1097
#define IDC_COLOR                       1098
#define IDC_ALLIES                      1099
#define IDC_CREDITS                     1100
#define IDC_ACTSLIKE                    1101
#define IDC_PROGRESS1                   1101
#define IDC_NODECOUNT                   1102
#define IDC_CAP                         1102
#define IDC_TECHLEVEL                   1103
#define IDC_FREE                        1103
#define IDC_PERCENTBUILT                1104
#define IDC_ID                          1104
#define IDC_PLAYERCONTROL               1105
#define IDC_TEAMTYPES                   1109
#define IDC_NEWTEAMTYPE                 1110
#define IDC_DELETETEAMTYPE              1111
#define IDC_LOADABLE                    1113
#define IDC_FULL                        1114
#define IDC_ANNOYANCE                   1115
#define IDC_GUARDSLOWER                 1116
#define IDC_RECRUITER                   1117
#define IDC_AUTOCREATE                  1119
#define IDC_PREBUILD                    1120
#define IDC_GROUP                       1122
#define IDC_WAYPOINT                    1123
#define IDC_SCRIPT                      1124
#define IDC_TASKFORCE                   1125
#define IDC_TRANSPORTWAYPOINT           1126
#define IDC_REINFORCE                   1127
#define IDC_DROPPOD                     1128
#define IDC_WHINER                      1129
#define IDC_LOOSERECRUIT                1130
#define IDC_AGGRESSIVE                  1131
#define IDC_SUICIDE                     1132
#define IDC_ONTRANSONLY                 1133
#define IDC_AVOIDTHREATS                1134
#define IDC_IONIMMUNE                   1135
#define IDC_TRANSPORTRETURNSONUNLOAD    1136
#define IDC_ARETEAMMEMBERSRECRUITABLE   1137
#define IDC_ISBASEDEFENSE               1138
#define IDC_ONLYTARGETHOUSEENEMY        1139
#define IDC_MINDCONTROLDECISION         1140
#define IDC_VETERANLEVEL                1143
#define IDC_TASKFORCES                  1144
#define IDC_UNITS                       1145
#define IDC_ADDUNIT                     1146
#define IDC_DELETEUNIT                  1147
#define IDC_NUMBERUNITS                 1148
#define IDC_UNITTYPE                    1149
#define IDC_DELETETASKFORCE             1150
#define IDC_ADDTASKFORCE                1151
#define IDC_ADD                         1154
#define IDC_REPEAT                      1156
#define IDC_TRIGGER                     1157
#define IDC_ADDTRIGGER                  1160
#define IDC_DELETETRIGGER               1161
#define IDC_FLAG1                       1162
#define IDC_PLACEONMAP                  1162
#define IDC_FLAG2                       1163
#define IDC_CLONE                       1163
#define IDC_FLAG3                       1164
#define IDC_FLAG4                       1165
#define IDC_FLAG5                       1166
#define IDC_EVENT                       1167
#define IDC_FLAG6                       1167
#define IDC_ADDEVENT                    1168
#define IDC_FLAG7                       1168
#define IDC_DELETEEVENT                 1169
#define IDC_FLAG8                       1169
#define IDC_ACTION                      1170
#define IDC_FLAG9                       1170
#define IDC_EVENTPARAM1                 1171
#define IDC_EVENTPARAM2                 1172
#define IDC_ADDACTION                   1173
#define IDC_DELETEACTION                1174
#define IDC_EVENTTYPE                   1175
#define IDC_ACTIONPARAM1                1176
#define IDC_ACTIONWAYPOINT              1177
#define IDC_ACTIONTYPE                  1178
#define IDC_ACTIONPARAM2                1179
#define IDC_ACTIONPARAM3                1180
#define IDC_ACTIONPARAM4                1181
#define IDC_ACTIONPARAM5                1182
#define IDC_ACTIONPARAM6                1183
#define IDC_LABEL_E1                    1184
#define IDC_LABEL_E2                    1185
#define IDC_LABEL_A1                    1186
#define IDC_LABEL_A4                    1187
#define IDC_LABEL_A2                    1188
#define IDC_LABEL_A3                    1189
#define IDC_LABEL_A5                    1190
#define IDC_LABEL_A6                    1191
#define IDC_TRIGGER2                    1192
#define IDC_SCRIPTTYPE                  1193
#define IDC_PARAM                       1196
#define IDC_PDESC                       1198
#define IDC_AITRIGGERTYPE               1199
#define IDC_ENABLEALL                   1200
#define IDC_TEAMTYPE1                   1204
#define IDC_OWNER                       1205
#define IDC_TEAMTYPE2                   1206
#define IDC_DATALABEL                   1210
#define IDC_DATA                        1211
#define IDC_FLOAT1                      1213
#define IDC_FLOAT2                      1215
#define IDC_FLOAT3                      1216
#define IDC_ENABLED                     1218
#define IDC_POOL                        1219
#define IDC_MAPNAME                     1220
#define IDC_BROWSE                      1221
#define IDC_IMPORTTREES                 1222
#define IDC_IMPORTOVERLAY               1223
#define IDC_IMPORTUNITS                 1224
#define IDC_MULTIPLAYER                 1226
#define IDC_IMPORTFILE                  1228
#define IDC_LANGUAGE                    1231
#define IDC_VERSION                     1232
#define IDC_BUILTBY                     1233
#define IDC_LDESC                       1233
#define IDC_LNAME                       1234
#define IDC_LNEXTSCENARIO               1235
#define IDC_LALTNEXTSCENARIO            1236
#define IDC_LNEWINIFORMAT               1237
#define IDC_LCARRYOVERCAP               1238
#define IDC_LENDOFGAME                  1239
#define IDC_LSKIPSCORE                  1240
#define IDC_LONETIMEONLY                1241
#define IDC_LSKIPMAPSELECT              1242
#define IDC_LOFFICIAL                   1243
#define IDC_LIGNOREGLOBALAITRIGGERS     1244
#define IDC_LTRUCKCRATE                 1245
#define IDC_LTRAINCRATE                 1246
#define IDC_LPERCENT                    1247
#define IDC_LMULTIPLAYERONLY            1248
#define IDC_LTIBERIUMGROWTHENABLED      1249
#define IDC_LVEINGROWTHENABLED          1250
#define IDC_LICEGROWTHENABLED           1251
#define IDC_LTIBERIUMDEATHTOVISCEROID   1252
#define IDC_LFREERADAR                  1253
#define IDC_LINITIME                    1254
#define IDC_LPLAYER                     1255
#define IDC_HUMANPLAYER                 1256
#define IDC_AUTOPROD                    1257
#define IDC_LHOUSE                      1258
#define IDC_LSTRENGTH                   1259
#define IDC_LPOS                        1260
#define IDC_LSTATE                      1261
#define IDC_LDIRECTION                  1262
#define IDC_LTAG                        1263
#define IDC_LP1                         1264
#define IDC_LP2                         1265
#define IDC_LP3                         1266
#define IDC_LP4                         1267
#define IDC_LP5                         1268
#define IDC_LAIREPAIRS                  1271
#define IDC_LENERGY                     1272
#define IDC_LUPGRADECOUNT               1273
#define IDC_LSPOTLIGHT                  1274
#define IDC_LUPGRADE1                   1275
#define IDC_LUPGRADE2                   1276
#define IDC_LUPGRADE3                   1277
#define IDC_LVERSION                    1279
#define IDC_LBUILTBY                    1280
#define IDC_LINFO                       1281
#define IDC_LDOWNLOAD                   1282
#define IDC_LPLAYERHOUSE                1283
#define IDC_LIMPORTOPTIONS              1284
#define IDC_DESC                        1285
#define IDC_LIQ                         1287
#define IDC_LEDGE                       1288
#define IDC_LSIDE                       1289
#define IDC_LCOLOR                      1290
#define IDC_LALLIES                     1291
#define IDC_LCREDITS                    1292
#define IDC_LACTSLIKE                   1293
#define IDC_LNODECOUNT                  1294
#define IDC_LTECHLEVEL                  1295
#define IDC_LBUILDACTIVITY              1296
#define IDC_LPLAYERCONTROL              1297
#define IDC_LNORMAL                     1298
#define IDC_LIONSTORM                   1299
#define IDC_LAMBIENT1                   1300
#define IDC_LLEVEL1                     1301
#define IDC_LAMBIENT2                   1302
#define IDC_LLEVEL2                     1303
#define IDC_LRED1                       1304
#define IDC_LGREEN1                     1305
#define IDC_LBLUE1                      1306
#define IDC_LRED2                       1307
#define IDC_LGREEN2                     1308
#define IDC_LBLUE2                      1309
#define IDC_LID                         1310
#define IDC_LP6                         1312
#define IDC_LTIBERIUMGROWS              1314
#define IDC_LTIBERIUMSPREADS            1315
#define IDC_LTIBERIUMEXPLOSIVE          1316
#define IDC_LDESTROYABLEBRIDGES         1317
#define IDC_LMCVDEPLOY                  1318
#define IDC_LINITIALVETERAN             1319
#define IDC_LFIXEDALLIANCE              1320
#define IDC_LHARVESTERIMMUNE            1321
#define IDC_LFOGOFWAR                   1322
#define IDC_LINERT                      1323
#define IDC_LIONSTORMS                  1324
#define IDC_LMETEORITES                 1325
#define IDC_LVISCEROIDS                 1326
#define IDC_INTRO                       1327
#define IDC_BRIEF                       1328
#define IDC_WIN                         1329
#define IDC_LOSE                        1330
#define IDC_STARTINGDROPSHIPS           1331
#define IDC_POSTSCORE                   1332
#define IDC_PREMAPSELECT                1333
#define IDC_CARRYOVERMONEY              1334
#define IDC_TIMERINHERIT                1335
#define IDC_FILLSILOS                   1336
#define IDC_LSTARTINGDROPSHIPS          1337
#define IDC_LCARRYOVERMONEY             1338
#define IDC_LINHERITTIMER               1339
#define IDC_LFILLSILOS                  1340
#define IDC_LMOVIES                     1341
#define IDC_LINTRO                      1342
#define IDC_LBRIEF                      1343
#define IDC_LWIN                        1344
#define IDC_LLOSE                       1345
#define IDC_LACTION                     1346
#define IDC_LPOSTSCORE                  1347
#define IDC_LPREMAPSELECT               1348
#define IDC_SIZEFRAME                   1349
#define IDC_LSIZE                       1350
#define IDC_USEABLEFRAME                1351
#define IDC_LUSEABLE                    1352
#define IDC_LTHEATER                    1353
#define IDC_MAPPROBLEMS                 1357
#define IDC_LPROBLEMSFOUND              1358
#define IDC_RULESLIKETS                 1360
#define IDC_ONLYORIGINAL                1364
#define IDC_LADDONNEEDED                1365
#define IDC_TILESET                     1366
#define IDC_OVERLAY                     1367
#define IDC_IMPORT                      1370
#define IDC_WIDTH                       1373
#define IDC_HEIGHT                      1374
#define IDC_BRUSHSIZE                   1377
#define IDC_SAVEOFTEN                   1378
#define IDC_NEWTRIGGER                  1383
#define IDC_TRIGGERTAB                  1393
#define IDC_TRIGGERTYPE                 1394
#define IDC_NEWEVENT                    1396
#define IDC_EVENTDESCRIPTION            1399
#define IDC_PARAMETER                   1401
#define IDC_PARAMVALUE                  1402
#define IDC_NEWACTION                   1403
#define IDC_ACTIONDESCRIPTION           1404
#define IDC_GLOBAL                      1405
#define IDC_DESCRIPTION                 1407
#define IDC_COUNTRY                     1411
#define IDC_DISABLED                    1412
#define IDC_LTRANSPORTWAYPOINT          1413
#define IDC_SINGLE                      1414
#define IDC_MULTI                       1415
#define IDC_CREATE                      1415
#define IDC_COMPRESS                    1417
#define IDC_NOCOMPRESSION               1418
#define IDC_PREVIEWMODE                 1419
#define IDC_EXISTINGPREVIEW             1420
#define IDC_NOPREVIEW                   1421
#define IDC_PROGRESS                    1423
#define IDC_EASY                        1424
#define IDC_MEDIUM                      1425
#define IDC_MMX                         1425
#define IDC_HARD                        1426
#define IDC_MMX2                        1426
#define IDC_STANDARD                    1426
#define IDC_MEATGRIND                   1427
#define IDC_NAVALWAR                    1428
#define IDC_NUKEWAR                     1429
#define IDC_AIRWAR                      1430
#define IDC_MEGAWEALTH                  1431
#define IDC_DUEL                        1432
#define IDC_COOPERATIVE                 1433
#define IDC_MINPLAYERS                  1434
#define IDC_TEAMGAME                    1434
#define IDC_MAXPLAYERS                  1435
#define IDC_LABEL                       1435
#define IDC_UPDATELIST                  1436
#define IDC_DOWNLOADLIST                1437
#define IDC_PROGLABEL                   1438
#define IDC_CHANGELOCAL                 1439
#define IDC_CHANGE                      1440
#define IDC_AITRIGGERS                  1440
#define IDC_AVAIL                       1442
#define IDC_USED                        1443
#define IDC_REMOVE                      1444
#define IDC_MCD_L                       1446
#define IDC_PREVIEW                     1448
#define IDC_CONDITION                   1449
#define IDC_NUMBER                      1450
#define IDC_BASEDEFENSE                 1452
#define IDC_SKIRMISH                    1453
#define IDC_MULTISIDE                   1456
#define IDC_SCRIPTS                     1457
#define IDC_REPORT                      1458
#define IDC_CAPTION                     1459
#define IDC_COMBO1                      1460
#define IDC_LICENSE_AND_COPYRIGHT       1461
#define IDC_PREFER_LOCAL_THEATER_INI_FILES 1462
#define IDC_PREFER_LOCAL_THEATER_FILES  1463
#define ID_FILE_OPENMAP                 40001
#define ID_FILE_SAVEAS                  40002
#define ID_FILE_QUIT                    40003
#define ID_OPTIONS_TIBERIANSUNOPTIONS   40004
#define ID_OPTIONS_EXPORTRULESINI       40005
#define ID_HELP_INFO                    40006
#define ID_MAPVIEW                      40007
#define ID_INSERT_TREES                 40008
#define ID_INSERT_UNITS                 40009
#define ID_INSERT_BUILDINGS             40010
#define ID_INSERT_INFANTRY              40011
#define ID_FILE_IMPORTMOD               40016
#define ID_FILE_RUNTIBERIANSUN          40017
#define IDS_BUILTBY                     40017
#define ID_DEBUG_EXPORTMAPPACK          40018
#define IDS_VERSIONTEXT                 40018
#define ID_DEBUG_EXPORTMAPPACKNOSECTIONS 40019
#define IDS_VERSION                     40019
#define IDS_VERSIONTEXTTS               40020
#define ID_HELP_TIPOFTHEDAY             40022
#define ID_OPTIONS_SIMPLEVIEW           40023
#define ID_OPTIONS_SHOWMINIMAP          40024
#define ID_FILE_VALIDATEMAP             40025
#define ID_MAPPACKTOOLS_EXPORTMAPPACK   40031
#define ID_MAPPACKTOOLS_IMPORTMAPPACKRAWHEXDATA 40032
#define ID_MAPPACKTOOLS_USEFORMAT80DECODINGONBINARYFILE 40033
#define ID_MAPPACKTOOLS_USEFORMAT80ENCODINGONBINARYFILE 40034
#define ID_MAPPACKTOOLS_EXPORTONLYSECTION1OFMAPPACKRAWHEXDATABASE64DECODED 40035
#define ID_EDIT_BASICSETTINGS           40036
#define ID_EDIT_SINGLEPLAYERSETTINGS    40037
#define ID_EDIT_SPECIALFLAGS            40038
#define ID_EDIT_HOUSES                  40039
#define ID_EDIT_MAP                     40040
#define ID_EDIT_TRIGGERS                40041
#define ID_EDIT_TAGS                    40042
#define ID_EDIT_LIGHTING                40043
#define ID_EDIT_SCRIPTS                 40044
#define ID_EDIT_TEAMS                   40045
#define ID_EDIT_TASKFORCES              40046
#define ID_EDIT_AITRIGGERS              40047
#define ID_EDIT_AITRIGGERENABLING       40048
#define ID_EDIT_INIEDITING              40049
#define ID_TERRAIN_HEIGHTENGROUND       40053
#define ID_TERRAIN_LOWERGROUND          40054
#define ID_TERRAIN_PAINT                40055
#define ID_TERRAIN_RISETILE             40060
#define ID_TERRAIN_RAISETILE            40062
#define ID_TERRAIN_LOWERTILE            40063
#define ID_TERRAIN_FLATTEN              40064
#define ID_TERRAIN_CLOAK                40065
#define ID_TERRAIN_SHOWEVERYTILE        40066
#define ID_TERRAIN_SHOWALLFIELDS        40071
#define ID_TERRAIN_HIDEFIELD            40072
#define ID_EDIT_TRIGGEREDITOR           40076
#define ID_MAPTOOLS_CHANGEMAPHEIGHT     40077
#define ID_EDIT_GLOBALVARIABLES         40082
#define ID_MAPTOOLS_AUTOLEVEL           40085
#define ID_MAPTOOLS_FRONTCLIFF          40092
#define ID_MAPTOOLS_BACKCLIFF           40093
#define ID_MAPTOOLS_AUTOCREATESHORES    40096
#define ID_OPTIONS_DISABLEAUTOSHORE     40104
#define ID_OPTIONS_DISABLEAUTOLAT       40105
#define ID_ONLINE_AUTOMATICUPDATE       40106
#define ID_EDIT_COPYWHOLEMAP            40109
#define ID_EDIT_PASTEWHOLEMAP           40110
#define ID_MARBLEMADNESS                40115
#define ID_OPTIONS_SOUNDS               40118
#define ID_ONLINE_UNOFFICIALSUPPORTFORUM 40119
#define ID_OPTIONS_DISABLESLOPECORRECTION 40120
#define ID_OPTIONS_SHOWBUILDINGOUTLINE  40123
#define ID_FILE_FILE1                   40129
#define ID_FILE_FILE2                   40130
#define ID_FILE_FILE3                   40131
#define ID_FILE_FILE4                   40132
#define ID_MAPTOOLS_SEARCHWAYPOINT      40133
#define ID_MAPTOOLS_TOOLSCRIPTS         40135
#define ID_HELP_SHOWLOGS                40138
#define ID_HELP_                        40139
#define ID_HELP_SHOWLOGS40140           40140
#define ID_OPTIONS_SMOOTHZOOM           40141
#define ID_OPTIONS_USEDEFAULTMOUSECURSOR 40142

#define IDS_LINEARVERSION               57604
#define IDC_TOOLTIPCENTER               65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        300
#define _APS_NEXT_COMMAND_VALUE         40144
#define _APS_NEXT_CONTROL_VALUE         1464
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
